### ISSUE TITLE
关于新建应用页面的设计

### ISSUE THREAD

**Issue by XZYW** [Serverless-Devs/Serverless-Devs-VSCode-Plugin#3]
从侧边栏点击新建之后能够进入下面的页面，它用于代替s init xx这个命令。
![BE5BACC1-BBDA-4BE2-8CF6-0A1308C967EF](https://user-images.githubusercontent.com/42271882/169708917-94f22b12-2dc8-49a0-889a-a569dc01db1b.png)
但是有个问题是，如果后面开发者们持续地贡献应用到registry上，应用多了，这个展示不下怎么办。vscode插件的开发有没有办法实现按需加载？

**Comment by XZYW** [comment]
或者可以展示热度最高的一部分，因为大部分的人知道自己需要什么，会通过搜索框去搜索，也许这边展示热度最高的一些就行了。

**Comment by anycodes** [comment]
可以直接通过接口拉回来。不用额外处理（指的是分页啥的）

**Comment by XZYW** [comment]
嗯。。。现阶段不用处理也没关系。
